###

GET http://localhost:3000/user

###

POST http://localhost:3000/user
Content-Type: application/json

[
    {
        "firstName": "sunghyun",
        "lastName": "cho"
    }, {
        "firstName": "asgsdgaegawega",
        "lastName": "whdhghd"
    }, {
        "firstName": "eagewgawgw",
        "lastName": "whdhghd"
    }
]